### ISSUE TITLE
Inventory questions

### ISSUE THREAD

**Issue by bpbond** [FoRTExperiment/fortedata#10]
* `Health_status` - L, D, and M. What is "M"?
* `Canopy_status` - there are blank values; is this OK? What does SA stand for?
* There are a number of different codes currently used for an unknown tree, including "unknown", "?", "snag", and "UNKNOWN". I'd like to standardize on one, ideally four letters to match everything else. How does "????" work?
* Row 791 of the inventory table has "REDACT" in the `DBH_cm` column, which forces the entire column to be character, which isn't great. What is this? Can we change to a flag, so that `DBH_cm` is cleanly numeric please?

**Comment by atkinsjeff** [comment]
1) - M stands for "moribund" i.e. it doesn't look great to the point a notation was warranted. 
2) - Canopy_status  SA? That's a Lisa question, I have asked her on Slack
3) - I am okay with ???? My apologies there. I thought I had caught that error
4) - Will do.

Let me address issues 3 and 4 right now. 

--jeff

**Comment by atkinsjeff** [comment]
SA is sapling

**Comment by bpbond** [comment]
Everything on the list above is resolved, closing.
