### ISSUE TITLE
Use of factors in fortedata

### ISSUE THREAD

**Issue by bpbond** [FoRTExperiment/fortedata#11]
How much / should we use factors in the `fortedata` datasets? As @ashiklom [notes](https://github.com/FoRTExperiment/fortedata/pull/9#discussion_r319767877), they provide run-time consistency check for free, and a sensible, consistent default plotting order. On the other, as I responded, they can be confusing and a source of hard-to-figure-out bugs for beginners.

**Comment by atkinsjeff** [comment]
note...we settled on character class for everything.
