### ISSUE TITLE
Standardize species codes

### ISSUE THREAD

**Issue by ashiklom** [FoRTExperiment/fortedata#13]
Where possible, we should use the official [USDA NRCS plants database](https://plants.sc.egov.usda.gov/java/) species codes, or at least create a table matching field shorthand to those codes.

From a quick pass through the current data, only the following need to be corrected:

- `POGR` --> [`POGR4`](https://plants.usda.gov/core/profile?symbol=POGR4)
- `ACSA` --> [`ACSA3`](https://plants.usda.gov/core/profile?symbol=ACSA3)
- `AMEL` --> [`AMELA`](https://plants.usda.gov/core/profile?symbol=AMELA)
- `BEAL` --> [`BEAL2`](https://plants.usda.gov/core/profile?symbol=BEAL2)
- `POTR` --> [`POTR5`](https://plants.usda.gov/core/profile?symbol=POTR5)

(There are also a few isolated instances of what I'm guessing are typos, e.g. `QUR` --> `QURU`; `ADRU` --> `ACRU`...?).

Factors may be an effective way to enforce this (e.g. #11 #2).

**Comment by atkinsjeff** [comment]
fixed.
