### ISSUE TITLE
Overstory biomass

### ISSUE THREAD

**Issue by bpbond** [FoRTExperiment/fortedata#21]
Removed from #17 (see [this comment](https://github.com/FoRTExperiment/fortedata/pull/17#issuecomment-601494743)).

```
  # bring in the allometry values
  allo.df <- read_csv_file("biomass_allometry_table.csv") #this has the same equations AmeriFlux uses

  # changing column names
  names(allo.df)[1] <- paste("Species")

  # Add in the allometries
  inv <- merge(inv, allo.df)

  #calculates biomass in units of kg
  inv$Biomass_kg <- inv$a.biomass * inv$DBH_cm ^ inv$b.biomass
```

We can consider adding `fd_biomass()` or something in a later version.  cc @atkinsjeff 

[biomass_allometry_table.csv.zip](https://github.com/FoRTExperiment/fortedata/files/4358465/biomass_allometry_table.csv.zip)

**Comment by atkinsjeff** [comment]
added calc_biomass()
