### ISSUE TITLE
Things to fix or look at asap

### ISSUE THREAD

**Issue by bpbond** [FoRTExperiment/fortedata#22]
## General

- [x] Timestamp columns should have a consistent name throughout the package
- [x] Generally just have a timestamp column, not "Year" in addition? 
- [x] Own-line comments should be '#' followed by space followed by a capitalized letter
- [x] Datasets should be checked for consistent rep, plot, subplot 
- [x] Function documentation should say "XXX data" not "Return XX data"
- [x] Do we want the summary functions?
- [x] Naming consistency: in general let's use `this_column` not `this.column` or `thisColumn`
- [ ] At end run code through `styler` package?
- [x] Add @author fields

## Tests

- [x] Once metadata is updated then other tests (e.g. `expect_is(dat$Year, "integer")` in `test.fd_remote_sensing.R` can be removed

## fd_belowground.R

- [x] `fd_soilCO` returns an NA DateTime column
- [X] Add `fd_soilCO` to `forte_table_metadata.csv`

## fd_leaf_physiology.R

- [x] Add all tables to `forte_table_metadata.csv`

## fd_litter.R

- [x] `fd_lai` is computing derived data (see discussion in #17 ); do we want to keep it?
- [x] Add all tables to `forte_table_metadata.csv`

## fd_remote_sensing.R

- [x] Add all tables to `forte_table_metadata.csv`

## fd_photosynthesis
- [x] has multiple timestamp/date columns - #23

**Comment by bpbond** [comment]
fd_photosynthesis has multiple timestamp/date columns (HHMMSS, Timestamp, DateTime); clean up, remove

**Comment by bpbond** [comment]
Let's remove the field descriptions in functions' documentation entirely and just depend on metadata table--that would be a LOT easier. So we'll want a `fd_metadata(dataset = NULL)` function that returns that information.

**Comment by atkinsjeff** [comment]
I am revisiting all the column heading x_x stuff now.
