### ISSUE TITLE
Timestamps in photosynthesis

### ISSUE THREAD

**Issue by bpbond** [FoRTExperiment/fortedata#23]
The photosynthesis data have both `HHMMSS` and `Timestamp` fields. But they don't match up:

```R
> x <- fd_photosynthesis()
> x$HHMMSS[1]
[1] "15:09:39"
> x$Timestamp[1]
[1] "2018-08-02 15:06:58 EDT"
```

What's the deal here? Are these instrument outputs, and if so, do we know why they don't match? Can we remove `HHMMSS` before returning data to the user?

Thanks.

**Comment by lisahaber** [comment]
Hi Ben,

The "Timestamp" field is something we manufactured, not an instrument output. The HHMMSS component of "Timestamp" is taken from the file header info, which I believe includes the time the file was opened. The "HHMMSS" is the time when the data were logged.

**Comment by bpbond** [comment]
Thanks. So `HHMMSS` is the true timestamp of the observation, then, for the day and year given in the `Filename_date` field?

**Comment by lisahaber** [comment]
Correct.
