### ISSUE TITLE
Timestamps need timezones

### ISSUE THREAD

**Issue by bpbond** [FoRTExperiment/fortedata#24]
What were field instruments set to? I assume EDT?

@kaylamathes 
@atkinsjeff 
@lisahaber 

Thanks.

**Comment by atkinsjeff** [comment]
EDT!

**Comment by bpbond** [comment]
So if this is the Gough lab standard, OK, but be aware that networks like FLUXNET, Ameriflux, etc., strongly recommend always using standard time. For off-season lab measurements, or November sampling trips, are instruments still EDT, or EST? Anyway we'll just want to be careful about this.

**Comment by atkinsjeff** [comment]
Good question I'd rather use EST. I will double check.

Jeff Atkins, Ph.D
Department of Biology
Virginia Commonwealth University

**Comment by atkinsjeff** [comment]
adjusted all calls to `....., tz = "America/Detroit")`
