### ISSUE TITLE
Where are treatment assignments?

### ISSUE THREAD

**Issue by bpbond** [FoRTExperiment/fortedata#32]
Am I missing something completely obvious? Where are the treatment (0/45/65/85) and cut (top-down, bottom-up) assignments? I was expecting them in the plot or subplot tables, but they're not.

😕

**Comment by atkinsjeff** [comment]
That would be a handy thing to add in there, huh?

**Comment by atkinsjeff** [comment]
These are added and will be in the next merge from my local branch. I added them in the plot_metadata file, do they need to be anywhere else?

**Comment by atkinsjeff** [comment]
Done. Added in plot_metadata

**Comment by atkinsjeff** [comment]
Done.

**Comment by atkinsjeff** [comment]
It appears, unless I am missing it, that there is no current way to bring that information into the workspace via a function.

**Comment by bpbond** [comment]
>It appears, unless I am missing it, that there is no current way to bring that information into the workspace via a function.

😕 why?

**Comment by atkinsjeff** [comment]
I dunno. I put a draft function `fd_treatments()` in` fd_plots.R`

Putting everything on here so I can keep track. Also not to self that ` fd_plots.R` still have the original function documentation and needs to be changed.

**Comment by atkinsjeff** [comment]
I put in a non-obvious place, the `fd_subplots()` function. And that one works better. I am going to delete the new function addition previous.
