### ISSUE TITLE
Need way to include project narrative/funded proposal

### ISSUE THREAD

**Issue by atkinsjeff** [FoRTExperiment/fortedata#35]
I have a formatted version of the Proposal (in yr Slack DMs @bpbond  ). What are thoughts on the best way to include this in fortedata? Including, what folder should it be in? How should it be accessible? Should it be converted to Markdown?

**Comment by bpbond** [comment]
Maybe this way? http://www.markvanderloo.eu/yaRb/2019/01/11/add-a-static-pdf-vignette-to-an-r-package/

**Comment by atkinsjeff** [comment]
Trying it out. I am going to look at the vignettes this week too. I had vignettes in forestr, but for some reason my laptop has had an issue with pdf vignettes. Some MikTek error somewhere.

**Comment by atkinsjeff** [comment]
The pdfpages package doesn't seem to be available. Diggin' into that.

**Comment by bpbond** [comment]
Ugh, I didn't think that was needed. It would good not to add another dependency unless absolutely necessary.

**Comment by atkinsjeff** [comment]
Looking for workaround. Need this for Gough's GEB paper too and the PCL
data. On it. Youngest kid needs my laptop for a class meeting, but I will
get it today. If you see anything else or know any other way off hand,
let me know. But otherwise I got it.

Jeff Atkins, Ph.D
Department of Biology
Virginia Commonwealth University

**Comment by atkinsjeff** [comment]
Done.
