### ISSUE TITLE
Unique tree identifiers in fd_leaf_spectrometry & elsewhere

### ISSUE THREAD

**Issue by lisahaber** [FoRTExperiment/fortedata#46]
The leaf spectral data set currently lacks a column for unique tree ID/sample. This is needed in case anyone wants to parse the data by individual leaf or tree crown, rather than subplot and/or species.

Here are a couple of things currently complicating the leaf physiology & spectral data -- specifically, combining the Subcanopy & Canopy data sets into one data product -- but all should be fixable. Happy to help in any ways I can.

(1) The Subcanopy (data from all replicates) and Canopy (additional crown-leaf data from just the D replicate) data sets use different naming conventions for samples. The naming schemes are as follows:
Subcanopy: Species + Sample are unique combinations within each Subplot, with one leaf coming from each individual stem selected. So, to know what stem you're talking about within the entire FoRTE experiment, you'd combine Subplot ID + Species + Sample (e.g. A01E_acru_01). Each of the stems is the same year to year (with occasional noted exceptions where something died & a replacement was selected), so you can look at leaf phys trends from discrete plants over time, if desired.

Canopy: Because all data came from one replicate (D), and several leaves were chosen from each stem, I used a different naming convention. Here, the tree has a unique identifier, but the sample refers to a leaf from that tree. The species of the tree (either ACRU, POGR, or QURU) is included in the tree identifier. So an example would be 1EP1_01: this would parse to Subplot D01E, POGR 1, Leaf 1; or 1EP1_02: D01E, POGR 1, Leaf 2.

(2) For added fun, I changed the naming convention for the Canopy data set in 2019. Formerly I had used the abbreviation "Can" in file names to denote canopy samples; this was before I came up with tree IDs. Lookup table attached should resolve the issue between 2018 & 2019 data and **we are keeping the 2019 convention**.

Let me know if any/all of this needs further explanation and again, happy to help. I will make sure all the 2018 & 2019 data for Canopy & Subcanopy are available in the FoRTE data folder, for starters.

Thanks!

PS -- Uploading lookup table as a .xlsx because .csv is not supported?!??!?!

[DRep_canopy_tree_lookup_table.xlsx](https://github.com/FoRTExperiment/fortedata/files/4659511/DRep_canopy_tree_lookup_table.xlsx)

**Comment by atkinsjeff** [comment]
Looking at this right now

` x <- fd_leaf_spectrometry()
 unique(x$tree_id)
 [1] "CAN01" "CAN02" "CAN03" "CAN04" "CAN05" "CAN06"
 [7] "CAN07" "CAN08" "CAN09" "CAN10" "CAN11" "CAN12"
[13] "CAN13" "CAN14" "CAN15"`

**Comment by atkinsjeff** [comment]
But I have added this into the package, this of course only takes care of the 2018 data. 2019 is not in here yet, but can be addressed.
