### ISSUE TITLE
fd_canopy_structure() 2018 data

### ISSUE THREAD

**Issue by lisahaber** [FoRTExperiment/fortedata#47]
Multiple entries (usually two) in 2018 -- need a date column, or some indicator about the point in time when they were collected that year.

Also, it appears that most subplots were sampled twice that year, but B02E, B02W have zero entries for rugosity; A02E has three; A04W has one; C02W has four. Any idea what happened?

**Comment by atkinsjeff** [comment]
it is just transect level data....meaning that each plot has a NS and EW transect. Just average them. Putting this in here even though we talked.
