### ISSUE TITLE
calc_lai() returns its results invisibly

### ISSUE THREAD

**Issue by bpbond** [FoRTExperiment/fortedata#52]
It shouldn't.

**Comment by atkinsjeff** [comment]
No, it shouldn't. It was working previously. Hmmmm.

Jeff Atkins, Ph.D
Department of Biology
Virginia Commonwealth University

**Comment by bpbond** [comment]
I think line 234 in utilities should just be

```R
weak_as_tibble(lai)
```

**Comment by kdorheim** [comment]
Follow up comment/question what are the units on the lai data? Including it on the documentation would be helpful.

**Comment by bpbond** [comment]
Square meters of leaf per square meters of ground area, i.e. unitless.
