### ISSUE TITLE
help(fortedata) returns nothing

### ISSUE THREAD

**Issue by kdorheim** [FoRTExperiment/fortedata#54]
```
> help(fotedata)
No documentation for ‘fotedata’ in specified packages and libraries:
you could try ‘??fotedata’
```
```
??fortedata 
no results found
```

The help functionality is standard and heavily relied upon by users, it might even be a CRAN requirement, this should probably be set up sometime soon.

**Comment by bpbond** [comment]
Incorrect invocation; `help(package="fortedata")` works as expected.
