### ISSUE TITLE
calc_biomass documentation

### ISSUE THREAD

**Issue by kdorheim** [FoRTExperiment/fortedata#55]
There is minimal documentation for the data frame returned with `calc_biomass` and is not included in `fd_metadata`. 

In the `@return` section can add some notes with the form, with an item for each column, this documentation will show up with the help(fortedata) and will to the pkgdown documentation. 

```
#' \describe{
#'   \item{One}{First item}
#'   \item{Two}{Second item}
#' }
```

**Comment by atkinsjeff** [comment]
Hmmm got it. Working on it now. I was probably thinking of this in a backwards way intiailly.
