### ISSUE TITLE
Git conflict lines in R files

### ISSUE THREAD

**Issue by bpbond** [FoRTExperiment/fortedata#68]
Currently four files have git conflict lines (e.g. `<<<<<<< HEAD`) in them:

fd_belowground_vignette.R
fd_examples.R:
fd_leaf_physiology_vignette.R
fd_remote_sensing_vignette.R

**Comment by bpbond** [comment]
@atkinsjeff Do you want me clean up?

**Comment by atkinsjeff** [comment]
Sure, if it is not too much trouble on your part. I haven't seen where the
conflicts are on my end.

Jeff Atkins, Ph.D
Department of Biology
Virginia Commonwealth University

**Comment by bpbond** [comment]
Actually I can't, since I don't know what the intended outcome is.

For example, lines 94-98 in the remote sensing vignette are:
```R
<<<<<<< HEAD
## ----rug, fig.width = 6, fig.height = 6, fig.align = "center", echo = FALSE----
=======
## ----rug, fig.height = 4, fig.width = 6, fig.align = "center"------------
>>>>>>> cb9893702271eb3ec6e45781def98757a5820179
x <- fd_canopy_structure()
```

This is `master` HEAD.

**Comment by atkinsjeff** [comment]
I think this is corrected. Not sure though.
