### ISSUE TITLE
udunits2 check fail on MAC OS

### ISSUE THREAD

**Issue by atkinsjeff** [FoRTExperiment/fortedata#71]
I am not sure exactly how to address this as it seems to be a general problem according to google.

![image](https://user-images.githubusercontent.com/8354517/101932359-a8f36500-3ba8-11eb-9c93-01a8e0b4dacf.png)

**Comment by bpbond** [comment]
It looks like `udunits2` hasn't been updated in a long time. Does this still need be addressed @atkinsjeff ?

**Comment by atkinsjeff** [comment]
Do you have an alternative to that package that would achieve the same end?

Jeff Atkins, Ph.D
Department of Biology
Virginia Commonwealth University

**Comment by bpbond** [comment]
I ask b/c I suspect the solution will be to force GA to use the older version.

**Comment by atkinsjeff** [comment]
I will kindly defer to you on how to do that, Google is unhelpful at the moment. And by Google I mean me using it, not Google failing as it did earlier today. There is no rush on this though, obviously.

**Comment by bpbond** [comment]
https://stackoverflow.com/questions/42287164/install-udunits2-package-for-r3-3

**Comment by atkinsjeff** [comment]
Package has been ORPHANED according to CRAN, but this issue seems to have resolved
