### ISSUE TITLE
Data Management vignette

### ISSUE THREAD

**Issue by atkinsjeff** [FoRTExperiment/fortedata#79]
A data management vignette has been added to `fortedata` with the intention of creating a universal, one-ring-to-rule-them-all system for guidance on data collection, management, etc.  I am opening this issue to have a platform to talk about where to take this for all.

**Comment by atkinsjeff** [comment]
It is fd_data_mgmt,Rmd

**Comment by camerclay** [comment]
@atkinsjeff do you think this issue can be closed? If not, I'm happy to help talk with the assigned members about how we can move forward on it.
