### ISSUE TITLE
Citation - specific data sets

### ISSUE THREAD

**Issue by bpbond** [FoRTExperiment/fortedata#8]
There will eventually be papers tied to specific datasets...but not yet. So I feel like every `fd_xxx()` function should end by calling a `data_conditions()` function, something like this:

```R
data_conditions <- function(x, published = FALSE, contact_person, citation) {

    if(!published) {
        warning("These data are unpublished. Please contact ", contact_person, " to ask about using")
    }

    message("Data citation: ", citation)
    message("Contact person: ", contact_person)

   # add the above information to `x` as attributes...

    invisible(x)
}

**Comment by atkinsjeff** [comment]
working on trying this out, but having issues incorporating. 

` Error: 'data_conditions' is not an exported object from 'namespace:fortedata' `

**Comment by atkinsjeff** [comment]
Tagging in @bpbond 

I added section of code to utils.R

`# data conditions
# data.frame() if necessary
# not a user-facing function; document via roxygen?
data_conditions <- function(x, published = FALSE, contact_person, citation) {

  if(!published) {
    warning("These data are unpublished. Please contact ", contact_person, " to ask about using")
  }

  message("Data citation: ", citation)
  message("Contact person: ", contact_person)

  # add the above information to `x` as attributes...

  invisible(x)
}`

And as a test I revised `fd_inventory()` to this:
`fd_inventory <- function() {

  # Data Creation and Authorship Information
  contact_person <- "Jeff Atkins"
  citation <- "ESSD"

  inv <- read_csv_file("forte_inventory.csv")
  inv$date <- as.Date(inv$date, format = "%m/%d/%Y")

  inv <- split_subplot_id(inv)

  # Currently there's a bad entry in the table. Nuke it. Temporary
  inv$dbh_cm <- as.numeric(inv$dbh_cm)  # temporary, until we fix row 791

  inv <- inv[c("subplot_id", "replicate", "plot", "subplot","date","tag", "species", "dbh_cm", "health_status", "canopy_status", "notes")]

  weak_as_tibble(inv)

  # data conditions
  data_conditions(x, published = FALSE, contact_person, citation)
}
`

**Comment by atkinsjeff** [comment]
reinstating data conditions
